import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Container from "./components/Container";
import Hero from "./components/Hero";

export const metadata = {
  title: "Listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Hero/>
        <Container>
          {children}
        </Container>
        <Footer />
      </body>
    </html>
  );
}
